Afordin/aforshow-2024

app/other-cursor.tsx, package.json, pnpm-lock.yaml
Now the cursor render an image with the flag. This improves the UX for the window's users
- Issue Number
=> feat: Add twemoji support for flag emoji in OtherCursor component

app/components/Header.tsx, app/components/common/Countdown.tsx, app/components/ui/button.tsx, app/globals.css, tailwind.config.ts
- Added buttons from figma
- Update countdown component wrapper
- Fix size
- fix hover
Dont know if the secoundary its the button with border only, and dont know the ghost as well :C
=> Buttons ui

.vscode/css_custom_data.json, .vscode/extensions.json, .vscode/settings.json, app/components/common/Contributors.tsx, app/components/common/hooks/index.ts, app/components/common/hooks/useContributors.ts, app/globals.css, app/page.tsx, app/shared-space.tsx
I extracted the contributors section from Hackafor and implemented it in the project.
Additionally, I created the `.vscode` folder with some settings for the tailwind directives
[Issue #8](https://github.com/Afordin/aforshow-2024/issues/8)
[contributors.webm](https://github.com/user-attachments/assets/70df3004-53d2-4c21-8362-f144e2a9b26e)
=> Extract contributor section from Hackafor

.github/workflows/vercel-preview.yml, .github/workflows/vercel-prod.yml
Add CI/CD workflows to deploy vercel prod and preview versions
#21
=> Add vercel preview and prod workflows

app/components/Nav.tsx, app/components/WelcomeHero.tsx, app/components/common/Countdown.tsx, app/shared-space.tsx, tailwind.config.ts
Added a bit of responsive design to the hero and header (I don't know what to do with the 🐁).
[Issue #13](https://github.com/Afordin/aforshow-2024/issues/13)
[Screencast from 22-07-24 22:49:45.webm](https://github.com/user-attachments/assets/b66510c1-890a-4bfe-97cb-9b66c0b61ed3)
=> feat: hero responsive design

app/components/Schedule.tsx, app/components/common/Talk.tsx
This is just a proposal of responsive for Schedule section, I'm not a designer 😅
https://github.com/Afordin/aforshow-2024/issues/13
=> feat: Proposal of Schedule responsive

app/components/FAQ.tsx, app/components/common/Summary.tsx, app/page.tsx
Add FAQ Section 
https://github.com/Afordin/aforshow-2024/issues/17
=> feat: faq section

app/components/WelcomeHero.tsx
Add icons from lucide to buttons
Add icons from lucide to buttons
[Issue Number](https://github.com/Afordin/aforshow-2024/issues/31)
=> fix: add arrow-up-right to buttons

.github/workflows/vercel-preview.yml, .github/workflows/vercel-prod.yml
[feat] Updated actions/checkout to version v3
[fix] Vercel deploy
[feat] Added pnpm install to vercel-deploy* workflows
- Issue Number
=> feat: Added pnpm to vercel workflows, update to actions/checkout@v3

app/components/Sponsors.tsx
=> remove style attribute from Sponsors animation

app/components/Schedule.tsx, app/components/common/Talk.tsx
- Change diplay Talk from flex to grid
- Add padding on Talk
#13 #16 
Prev: 
https://github.com/user-attachments/assets/ed8fed4a-442f-486d-b1f5-95e64f3c521a
New:
https://github.com/user-attachments/assets/57b2f74d-3120-453d-9a02-7da89e6cdd1e
=> style(shedule): responsive talks

app/components/Hero.tsx
=> fix: padding removed

app/components/Footer.tsx, app/components/Nav.tsx, app/components/Sponsors.tsx, app/components/icons/Logo.tsx, app/globals.css, next.config.mjs
Next.config.mjs
I have updated the next config adding the remotePatterns, the previous configuration is deprecated in Next 14
I added cdn.jsdelivr.net to remote patterns for flags image
Logo.tsx
I have updated the stop-color in Logo svg to camel case (stopColor) for better compatibility with react 
Nav.tsx
I changed the <img> to next Image component for a better performance
Fix Responsive #59 
Sponsors.tsx
I have fixed the weird jump at the end, now it will not leave a gap before the end of the animation
Sorry por la calentada de hacer varias cosas en 1 pr 🙏🏾
=> Troubleshoot warnings, deprecated code and Sponsors animation

app/components/Footer.tsx
add smooth scrolling functionality
add smooth scrolling functionality to footer back to top button
- #55
=> 🎨 (Footer.tsx): add smooth scrolling functionality

app/components/Nav.tsx
=> 🎨 (Nav.tsx): Fix flags overflow

app/[userId]/opengraph-image.tsx, app/layout.tsx, app/opengraph-image.tsx
=> improve og images details

app/components/Ticket.tsx
add responsive into the ticket.tsx 
the ticket had a bug on mobile devices
- Issue Number
=> feat: :sparkles: add reponsive to the ticket.tsx

app/components/WelcomeHero.tsx
=> add twitch iframe

app/components/WelcomeHero.tsx
=> Fix Twitch iframe responsive

app/components/FAQ.tsx, app/components/Footer.tsx, app/components/Nav.tsx, app/components/Schedule.tsx, app/components/Ticket.tsx, app/components/TicketDownload.tsx, app/components/WelcomeHero.tsx, app/components/common/Contributors.tsx, app/components/common/Summary.tsx, app/components/common/Table.tsx, app/components/ui/button.tsx, app/page.tsx
=> improve responsive to all the web

README.md
update Screenshots 
- [x ] chore: updated dependencies and configuration files
update Screenshots 
- Issue Number
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
=> update Screenshots 
